# Use the official PHP-FPM image
FROM php:8.2-fpm

RUN echo "Building the Docker image for my PHP application" 

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer