version: '3'
services:
  web:
    build:
      context: nginx
    ports:
      - '8080:80'
    volumes:
      - ./src:/var/www/html
    links:
      - php-fpm
      - mysql

  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ./src:/var/www/html

  mysql:
    image: mysql:8.1.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'