version: '3'
services:
  web:
    build:
      context: nginx
    ports:
      - '8080:80'
    volumes:
      - ./src:/var/www/html
    links:
      - php-fpm
  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ./src:/var/www/html